name: essmohr
description: "A new Flutter project."
publish_to: 'none'

version: 6.0.0+6

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management & Utilities
  flutter_bloc: ^9.1.1
  get: ^4.6.5
  get_it: ^8.0.3
  rxdart: ^0.27.7
  dartz: ^0.10.1

  # HTTP & Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0


  # UI & UX
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  page_transition: ^2.0.9
  animated_theme_switcher: ^2.0.1-nullsafety.0
  theme_provider: ^0.6.0
  flutter_staggered_animations: ^1.0.0
  curved_navigation_bar: ^1.0.3
  toggle_switch: ^2.1.0
  flutter_svg: ^2.0.7
  rive: ^0.13.9
  substring_highlight: ^1.0.33
  adaptive_scrollbar: ^2.1.2

  # Navigation & App Lifecycle
  flutter_phoenix: ^1.1.0
  scroll_snap_list: ^0.9.1
  mat_month_picker_dialog: ^1.1.2

  # Localization & Assets
  easy_localization: ^3.0.3
  path_provider: ^2.1.1
  path: ^1.9.0

  # Media & Files
  image_picker: ^1.0.7
  image_cropper: ^9.1.0

  # Device & Permissions
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  uuid: ^4.5.1

  # Notifications & Dynamic Icons
  flutter_local_notifications: ^19.2.0
  #flutter_dynamic_icon: ^2.1.0

  flutter_app_badger: ^1.3.0

  # Background tasks
  #workmanager: ^0.5.2
  flutter_background_service: ^5.1.0

  # WebSocket
  web_socket_channel: ^3.0.0

  # Connectivity
  internet_connection_checker: ^3.0.1

  # Syncfusion Widgets
#  syncfusion_flutter_datepicker: ^26.1.40
  syncfusion_flutter_pdfviewer: ^29.1.41
  syncfusion_flutter_datepicker: ^29.1.41
  syncfusion_flutter_pdf: ^29.1.41
  syncfusion_flutter_core: ^29.1.41
#  syncfusion_flutter_pdfviewer:
#    path: packages/syncfusion_flutter_pdfviewer

  # Tables
  data_table_2: ^2.2.1

  # Custom Dialog

  awesome_dialog: ^3.2.1
  flutter_typeahead: ^4.0.0



  flutter_screenutil: ^5.9.3
  file_picker: ^10.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  retrofit_generator: ^9.2.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/icons/AppIcon.png
    - assets/jsonFiles/error.json
    - assets/jsonFiles/loading.json
    - assets/jsonFiles/empty.json
    - assets/jsonFiles/success.json
    - assets/jsonFiles/loadingcircles.json
    - assets/jsonFiles/splash.json
    - assets/images/44190-under-construction-1 (1).gif
    - assets/images/Logo.png
    - assets/images/login.jpg
    - assets/images/home.jpeg
    - assets/images/welcome.jpg
    - assets/images/warning.jpg
    - assets/images/error_bg.jpg
    - assets/images/tick.png

    - assets/images/city.jpg

    - assets/images/profile_male.png
    - assets/images/side_menu_backgroud.jpg
    - assets/icons/menu.png
    - assets/icons/search.png
    - assets/icons/notification.png
    - assets/icons/profile.png
    - assets/icons/salary.png
    - assets/icons/attendance.png
    - assets/icons/vacation.png
    - assets/icons/requests.png
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/Earth.svg
    - assets/images/settings_right_arrow_ic.svg
    - assets/Backgrounds/countries.png
    - assets/translations/
    - assets/Backgrounds/
    - assets/RiveAssets/
    - assets/images/NewDesign/image/splash/
    - assets/images/NewDesign/image/onboarding/
    - assets/images/NewDesign/image/login/
    - assets/images/NewDesign/image/tab/
    - assets/images/NewDesign/image/home/
    - assets/images/NewDesign/image/person/

    - assets/fonts/NewDesign/font/


  fonts:
    - family: IBMP
      fonts:
        - asset: assets/fonts/NewDesign/font/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/NewDesign/font/IBMPlexSansArabic-Light.ttf
          weight: 500

    - family: Nunito
      fonts:
       - asset: assets/fonts/NewDesign/font/Nunito-Regular.ttf
